# Generated by Django 2.0 on 2018-10-24 10:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='wallets.CreditCard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('credit_card', 'expires_at')},
        ),
    ]
